
Excluded:
  - samples/*

Lint/UselessAssign:
  Description: Disallows useless variable assignments
  Excluded:
  - src/web.cr
  Enabled: true
  Severity: Warning

Lint/UnusedArgument:
  Description: Disallows unused arguments
  IgnoreDefs: true
  IgnoreBlocks: false
  IgnoreProcs: false
  Excluded:
  - src/web.cr
  Enabled: true
  Severity: Warning

Lint/NotNil:
  Description: Identifies usage of `not_nil!` calls
  Excluded:
  - src/helpers/helpers.cr
  - src/delegators/user_delegarot.cr
  Enabled: true
  Severity: Warning
