Metrics/CyclomaticComplexity:
  Enabled: true
  Excluded:
    - src/helpers/helpers.cr

Naming/BlockParameterName:
  Enabled: false

Lint/UselessAssign:
  Enabled: true
  Excluded:
    - src/web.cr

Lint/SpecFilename:
  Excluded:
    - spec/initdb.cr
