# === Sam shortcut
# next lines are autogenerated and any changes will be discarded after regenerating
SAM_PATH ?= "./bin/sam"
.PHONY: sam
sam:
	$(SAM_PATH) $(filter-out $@,$(MAKECMDGOALS))
%:
	@:
# === Sam shortcut
