doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="color-scheme" content="light dark"

    title Method not allowed

    link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"

    link type="text/css" rel="stylesheet" href="/css/404.css"
  body
    #notfound
      .notfound
        .notfound-404
          h1 405
        h2 This request method is not allowed for this page.
        a href="/"
          span.arrow
          | Back to Homepage
